### PR TITLE
iOS environment variable support

### PR DESCRIPTION
**Pull request by Jasper-Bekkers**
This is quite hacky; but it enables the metal debug layer (by default). This same code could be used to add other environment variables.

Probably shouldn't be merged as-is.

### CODE REVIEW

**Comment by kali** [comment]
Mmm.. is this a way to set arbitrary env variables for the app process on the device ? Because IIRC dinghy expose a more or less generic way to do that from configuration that we never managed to get working for iOS through lldb... Could we consider binding it to this trick ?

**Comment by Jasper-Bekkers** [comment]
Yeah this is the way to set regular environment variables on iOS processes through lldb so you should be able to use this for that.

**Comment by kali** [comment]
It looks relatively straightforward if you feel like doing the patch, all in dinghy-lib/src/ios/device.rs: _envs is ignore in one or two places and should be pass down to the function that generates the lldb script...

**Comment by Jasper-Bekkers** [comment]
I can take a quick look.

**Comment by Jasper-Bekkers** [comment]
I think these changes ought to do it (at least for me they give me the right env vars now when launching for example with `--env={"RUST_BACKTRACE=1","TEST=23"}`).

**Comment by kali** [comment]
0.4.39 pushed ! enjoy ! thanks for the patch !

**Pull request merged**
